name: ResursBank
options:
  bundleIdPrefix: se.resursbank
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""

targets:
  ResursBank:
    type: application
    platform: iOS
    sources:
      - path: ResursBank
    settings:
      base:
        INFOPLIST_FILE: ResursBank/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: se.resursbank.app.native
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
